export const CHANGE_CATEGORY="CHANGE_CATEGORY"

export const GET_CATEGORIES="GET_CATEGORIES"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR'

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';   
export const USERS_ERROR = 'USERS_ERROR'

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';   
export const USER_ERROR = 'USER_ERROR'

export const GET_SITE_INFO = 'GET_SITE_INFO';
export const GET_SITE_INFO_SUCCESS = 'GET_SITE_INFO_SUCCESS';   
export const SITE_INFO_ERROR = 'SITE_INFO_ERROR'

export const GET_PRODUCTS="GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR'

export const GET_FEATURED_PRODUCTS="GET_FEATURED_PRODUCTS"
export const GET_FEATURED_PRODUCTS_SUCCESS="GET_FEATURED_PRODUCTS_SUCCESS"
export const FEATURED_PRODUCTS_ERROR = 'FEATURED_PRODUCTS_ERROR'

export const GET_FEATURED_CATEGORIES="GET_FEATURED_CATEGORIES"
export const GET_FEATURED_CATEGORIES_SUCCESS="GET_FEATURED_CATEGORIES_SUCCESS"
export const FEATURED_CATEGORIES_ERROR = 'FEATURED_CATEGORIES_ERROR'

export const GET_COMMENTS="GET_COMMENTS"
export const GET_COMMENTS_SUCCESS="GET_COMMENTS_SUCCESS"
export const COMMENTS_ERROR = 'COMMENTS_ERROR'

export const GET_PRODUCTS_BY_CATEGORY="GET_PRODUCTS_BY_CATEGORY"
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS="GET_PRODUCTS_BY_CATEGORY_SUCCESS"
export const PRODUCTS_BY_CATEGORY_ERROR = 'PRODUCTS_BY_CATEGORY_ERROR'

export const GET_PRODUCTS_BY_ID="GET_PRODUCTS_BY_ID"
export const GET_PRODUCTS_BY_ID_SUCCESS="GET_PRODUCTS_BY_ID_SUCCESS"
export const PRODUCTS_BY_ID_ERROR = 'PRODUCTS_BY_ID_ERROR'

export const GET_LIKES="GET_LIKES"
export const GET_LIKES_SUCCESS="GET_LIKES_SUCCESS"
export const LIKES_ERROR = 'LIKES_ERROR'

export const GET_LIKES_BY_PRODUCT="GET_FAVOURITES_BY_PRODUCT"
export const GET_LIKES_BY_PRODUCT_SUCCESS="GET_FAVOURITES_BY_PRODUCT_SUCCESS"
export const LIKES_BY_PRODUCT_ERROR = 'LIKES_BY_PRODUCT_ERROR'

export const GET_LIKES_BY_USER="GET_LIKES_BY_USER"
export const GET_LIKES_BY_USER_SUCCESS="GET_LIKES_BY_USER_SUCCESS"
export const LIKES_BY_USER_ERROR = 'LIKES_BY_USER_ERROR'

export const GET_RATES_BY_PRODUCT="GET_RATES_BY_PRODUCT"
export const GET_RATES_BY_PRODUCT_SUCCESS="GET_RATES_BY_PRODUCT_SUCCESS"
export const RATES_BY_PRODUCT_ERROR = 'RATES_BY_PRODUCT_ERROR'